name: Build FFX HP Restore

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Skonfiguruj MSVC (x86)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Skonfiguruj CMake (Ninja + MSVC x86)
        run: cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -B build ffx-hp-restore

      - name: Kompiluj
        run: cmake --build build

      - name: Uploaduj gotowy DLL
        uses: actions/upload-artifact@v4
        with:
          name: ffx_hp_restore
          path: build/ffx_hp_restore.dll
          if-no-files-found: error
